# Generated by Django 5.0.1 on 2024-01-22 19:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_user',
            fields=[
                ('username', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
                ('current_question', models.IntegerField(default=1)),
                ('previous_question', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('question_id', models.IntegerField(primary_key=True, serialize=False)),
                ('question_md', models.CharField(default='Enter a Valid markdown', max_length=255)),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('correct', models.CharField(max_length=255)),
                ('author', models.CharField(max_length=255)),
                ('authors_note', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_option', models.CharField(max_length=255)),
                ('status', models.BooleanField(default=False)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcq')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.custom_user')),
            ],
        ),
    ]
