# Generated by Django 4.2.5 on 2024-01-07 16:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Custom_user',
            fields=[
                ('user_id', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Mcq',
            fields=[
                ('question_id', models.AutoField(primary_key=True, serialize=False)),
                ('question', models.CharField(max_length=255)),
                ('a', models.CharField(max_length=255)),
                ('b', models.CharField(max_length=255)),
                ('c', models.CharField(max_length=255)),
                ('d', models.CharField(max_length=255)),
                ('correct', models.CharField(max_length=1)),
                ('positive_marks', models.IntegerField(default=4)),
                ('negative_marks', models.IntegerField(default=-2)),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('submission_id', models.AutoField(primary_key=True, serialize=False)),
                ('selected_option', models.CharField(max_length=1)),
                ('status', models.CharField(max_length=255)),
                ('question_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.mcq')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.custom_user')),
            ],
        ),
        migrations.AddField(
            model_name='custom_user',
            name='current_question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mcq'),
        ),
    ]
