# Generated by Django 4.2.5 on 2024-01-10 17:46

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='mcq',
            name='negative_marks',
        ),
        migrations.RemoveField(
            model_name='mcq',
            name='positive_marks',
        ),
        migrations.AddField(
            model_name='custom_user',
            name='previous_question',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='current_question',
            field=models.ForeignKey(default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.mcq'),
        ),
        migrations.AlterField(
            model_name='submission',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
