# Generated by Django 4.2.5 on 2024-01-11 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_mcq_negative_marks_remove_mcq_positive_marks_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
