# Generated by Django 4.2.5 on 2024-01-11 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_custom_user_user_id_alter_mcq_question_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='submission_id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
