# Generated by Django 4.2.5 on 2024-01-11 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_submission_submission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='current_question',
            field=models.IntegerField(default=1),
        ),
    ]
