# Generated by Django 4.2.5 on 2024-01-13 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_alter_custom_user_current_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mcq',
            name='correct',
            field=models.CharField(max_length=255),
        ),
    ]
