# Generated by Django 4.2.5 on 2024-01-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_mcq_correct'),
    ]

    operations = [
        migrations.AlterField(
            model_name='submission',
            name='selected_option',
            field=models.CharField(max_length=255),
        ),
    ]
