# Generated by Django 4.2.5 on 2024-01-13 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_alter_submission_selected_option'),
    ]

    operations = [
        migrations.RenameField(
            model_name='mcq',
            old_name='question',
            new_name='author',
        ),
        migrations.AddField(
            model_name='mcq',
            name='authors_note',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='mcq',
            name='question_md',
            field=models.CharField(default='Enter a Valid Markdown', max_length=255),
        ),
    ]
