# Generated by Django 4.2.5 on 2024-01-14 15:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_alter_custom_user_options_alter_custom_user_managers_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='custom_user',
            options={},
        ),
        migrations.AlterModelManagers(
            name='custom_user',
            managers=[
            ],
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='date_joined',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='email',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='groups',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='is_staff',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='is_superuser',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='last_login',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='password',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='user_permissions',
        ),
        migrations.RemoveField(
            model_name='custom_user',
            name='username',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='user_id',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='mcq',
            name='question_md',
            field=models.CharField(default='Enter a Valid markdown', max_length=255),
        ),
    ]
