# Generated by Django 4.2.5 on 2024-01-14 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_rename_customuser_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='user_id',
            new_name='username',
        ),
    ]
