# Generated by Django 4.2.5 on 2024-01-16 12:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_rename_user_id_custom_user_username'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
