# Generated by Django 4.2.5 on 2024-01-16 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_delete_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='custom_user',
            name='username',
            field=models.CharField(max_length=255, primary_key=True, serialize=False),
        ),
    ]
